site_name: DBMS NOTES

nav:
  - Dashboard: index.md
  - Units:
      - Unit 1: unit1.md
      - Unit 2: unit2.md
      - Unit 3: unit3.md
      - Unit 4: unit4.md
      - Unit 5: unit5.md
  - About: about.md



theme:
  name: material
  palette:
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate  # dark mode
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggestions
    - toc.integrated
    - content.code.annotate
    - content.code.copy
    - content.tabs.links
    - header.autohide
    - navigation.sections
    - navigation.instant
    - navigation.expand
    - search.share
    - announcement.bar
    - footer.social
    - footer.copyright
    - content.footer
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Aashritha014
      name: GitHub
  copyright: "✨ Made by Aashritha Reddy"

extraa_css:
  - css/custom.css

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde