site_name: DBMS Notes
nav:
  - Home: index.md
  - Unit 1: unit1.md
  - Unit 2: unit2.md
  - Unit 3: unit3.md
  - Unit 4: unit4.md
  - Unit 5: unit5.md
  - Made By: about.md
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate # dark mode
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggestions
    - toc.integrated
    - content.code.annotate
    - content.code.copy
    - content.tabs.links
    - header.autohide
    - navigation.sections
    - navigation.instant
    - navigation.expand
    - search.share
    - announcement.bar
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Aashritha014
      name: GitHub

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3